Update upload script

diff --git a/.bin/upload b/.bin/upload
--- a/.bin/upload
+++ b/.bin/upload
@@ -1,10 +1,52 @@
 #/usr/bin/env bash
 
-#Url of the server
+version="1.0"
+upload_path="/data/upload/"
+server="srv"
+#Url of the website (used for copying url to clipboard)
 url="http://upload.davidgoransson.se/"
 
+function print_help {
+    echo "Upload files to your remote server"
+    echo ""
+    echo "usage:"
+    echo "upload [FILE(s)]        Uploads files to the server"
+    echo "upload clean            Clean the directory of files"
+    echo "upload -h, --help       Prints this help dialog"
+    echo ""
+    echo "upload v$version by Rawa"
+    echo "www.davidgoransson.com"
+}
+
+#Check if correct number of arguments
+if [ "$#" -eq 0 ]; then
+    print_help
+    exit 1
+fi
+
+#If only one argument check if it is help or clean
+if [ "$#" -eq 1 ]; then
+    if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
+        print_help
+        exit 0
+    fi
+
+    if [ "$1" == "clean" ] ; then
+        #Print confirm box
+        read -p "Are you sure? " -n 1 -r
+        echo    # (optional) move to a new line
+        if [[ $REPLY =~ ^[Yy]$ ]]
+        then
+            #Clean upload folder
+            ssh $server "cd $upload_path ; rm * -rf"
+            exit 0
+        fi
+        exit 0
+    fi
+fi
+
 #Copy the files to the server
-scp $@ srv:/data/upload
+scp $@ $server:$upload_path
 
 #Copy url to clipboard (direct link if single file)
 if [ "$#" -eq 1 ]; then
